### PR TITLE
Add real colors

### PR DESCRIPTION
**Pull request by heytherewill**
### Summary
This applies a nice coat of paint to our apps to make them look like the designs on InVision. This new coat of paint showed some UI problems that were masked by the previous colors, so things look better now.

### Pull Request checklist
- [X] The code does not hinder the app's performance
- [X] The code does not introduce regressions
- [X] The code in this PR is tested thoroughly enough that changing the behavior to an incorrect one breaks tests
- [ ] One of our [live or file custom templates](https://github.com/toggl/android/tree/master/.idea/templates) was used in this PR

### Pointers
Go at it commit by commit and it should be a breeze. Do a functional test and check both light and dark themes

### Review template
- [ ] The code considers light and dark theme
- [ ] The code considers RTL and does not mention left/right
- [ ] The code considers i18n
  - [ ] There are no hardcoded strings in the UI
  - [ ] All strings are included in every language we support OR there's an issue requesting new translations
- [ ] There are no hard-coded numbers referring to dimensions or font sizes
- [ ] The code considers UI elements that are similar and extracts their similarities into styles to avoid duplication

## Merge permissions
Only myself

### CODE REVIEW

**Comment by heytherewill** [comment]
- They are the same color, I just needed to remove the elevation of the bottom bar. Fixed 👌 
- Will be fixed some other time
- Fixed 👌 
- I couldn't reproduce this one. Do you have repro steps? Seems potentially linked to bad state

**Comment by daividssilverio** [comment]
> They are the same color, I just needed to remove the elevation of the bottom bar. Fixed 👌

I was talking about this: They don't look the same:
| start card | bottom sheet |
| --- | --- |
| Screen Shot 2020-05-28 at 9 44 23 AM | Screen Shot 2020-05-28 at 9 44 28 AM |
| #FFFFFF | #F8EEF0 |

**Comment by daividssilverio** [comment]
> I couldn't reproduce this one. Do you have repro steps? Seems potentially linked to bad state

I couldn't at first, but I accidentally found it again 😆 . 
I managed to replicate by:
1. clear the app storage (optional)
2. open the app
3. go to another tab
4. go back to the main tab
5. click directly on the play button (or stop button)...

Actually, this wasn't introduced by your PR. It happens on master as well. Ignore the request for changes for that.

**Comment by heytherewill** [comment]
I haven't thouched the start/edit view at all (and I won't until it's done)

**Pull request merged**
